#ifndef __SYSCALL_HELPER_H
#define __SYSCALL_HELPER_H

enum {
    SYSCALL_ALLOC,
    SYSCALL_SCRPUT,
    SYSCALL_PRTPUT,
    SYSCALL_EXIT,
    SYSCALL_SLEEP,
    SYSCALL_GFX_WINDOW,
    SYSCALL_GFX_PUT_CHAR,
    SYSCALL_GFX_GET_TIME,
    SYSCALL_GFX_DRAW
};

#endif /* __SYSCALL_HELPER_H */
